apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: monitoring
  labels:
    crossplane.io/xrd: xmonitoringservices.saltpaas.x5.ru
    provider: monitoring-provider
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: saltpaas.x5.ru/v1alpha1
    kind: XMonitoringService
  writeConnectionSecretsToNamespace: crossplane-system
  resources:                                                                        
  - name: test
    base:
      apiVersion: monitoring.paas.crossplane.io/v1alpha1
      kind: Monitoring
      metadata:
       name: test
      spec:
        forProvider:
          configurableField: test
        providerConfigRef:
          name: example
